package by.bsuir.models.cooling.types;

/**
 * Created by SleepyOwl on 13.05.2017.
 */
public enum CoolingType {

    NATURAL_AIR,
    FORCED_AIR,
    FORCED_LIQUID,
    NATURAL_EVAPORATION,
    FORCED_EVAPORATION,

    //Для неопределенных зон
    FORCED_AIR_OR_NATURAL_AIR,
    FORCED_AIR_OR_FORCED_LIQUID,
    FORCED_LIQUID_OR_NATURAL_EVAPORATION,
    FORCED_LIQUID_OR_NATURAL_EVAPORATION_OR_FORCED_EVAPORATION,
    NATURAL_EVAPORATION_OR_FORCED_EVAPORATION,

    //для зон с воздушным охлаждением
    AIR_HERMETIC_INTERNAL,
    AIR_HERMETIC_EXTERNAL,
    AIR_PERFORATED,
    AIR_BLOWN,


    ERROR
}
